### ISSUE TITLE
[debian 11] install fails

### ISSUE THREAD

**Issue by ektor5** [zeppaman/bashy#10]
# Bug: Install fails
Install script fails 

# Steps to reproduce 
```
git clone
./bashy/install.sh 
```

# Output
```
go ok
/home/ektor5/.zshrc: line 176: syntax error in conditional expression: unexpected token `<'
/home/ektor5/.zshrc: line 176: syntax error near `5.<1'
/home/ektor5/.zshrc: line 176: `    [[ $ZSH_VERSION == 5.<1->* ]] && return 0'
task does not exist. installing
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  9634  100  9634    0     0  40822      0 --:--:-- --:--:-- --:--:-- 40995
go-task/task info checking GitHub for latest tag
go-task/task debug http_download https://github.com/go-task/task/releases/latest
go-task/task info found version: 3.17.0 for v3.17.0/linux/amd64
go-task/task debug downloading files into /tmp/tmp.TyUz8sViIa
go-task/task debug http_download https://github.com/go-task/task/releases/download/v3.17.0/task_linux_amd64.tar.gz
go-task/task debug http_download https://github.com/go-task/task/releases/download/v3.17.0/task_checksums.txt
go-task/task info installed ./bin/task
task: No Taskfile found in "/home/ektor5". Use "task --init" to create a new one
cp: cannot stat './out/debug/bashy': No such file or directory
```

# Environment
 - Debian 11 
 - zsh 5.8 (x86_64-debian-linux-gnu)
- grml zsh config

**Comment by ektor5** [comment]
Investigated a bit:
```
/home/ektor5/.zshrc: line 176: syntax error in conditional expression: unexpected token `<'
/home/ektor5/.zshrc: line 176: syntax error near `5.<1'
/home/ektor5/.zshrc: line 176: `    [[ $ZSH_VERSION == 5.<1->* ]] && return 0'
```
This is due to sourcing `.zshrc` from bash, changing interpreter fixes this.

```
go-task/task info installed ./bin/task
task: No Taskfile found in "/home/ektor5". Use "task --init" to create a new one
```
Entering the directory `bashy` fixes this.

Few other issues:
 - bashy requires Go version >= 1.16, Debian 11 provides 1.15. Removed and let bashy install its own. 
 - install.sh wants to install bashy into `/usr/bin`, requires root. Changing directory to `~/bin` fixes the issue.

**Comment by zeppaman** [comment]
Hello @ektor5 and thank you for your suggestion.
Now I released ready-to-use binaries compiled by CI/CD pipelines.  The installation is now a single-line script and doesn't have any strong requirements:

``` bash
curl -LO https://github.com/zeppaman/bashy/releases/download/latest/bashy.linux &&  install  -m 0755 ./bashy.linux /usr/bin/bashy && rm ./bashy.linux && echo 'export PATH="$PATH:$HOME/.bashy/bin"'>>~/.bashrc &&  echo 'export PATH="$PATH:$HOME/.bashy/bin"'>>~/.profile &&  echo 'export PATH="$PATH:$HOME/.bashy/bin"'>>/etc/environment && export PATH="$PATH:$HOME/.bashy/bin"
```

limitation so far:
- we have only one binary for each OS (no variants for different architectures, for example, arm)
- we have not any binary for macOS
- tested in Debian, Ubuntu, alpine 

I hope that now the installation process will be smoother and easier. Moreover, the installation is now very simple (download, move the executable to the bin folder then add the path of bashy to PATH) so I think will be very easier for a user to tune it.

Any suggestion of feedback is welcome!
