### ISSUE TITLE
Adding logging system

### ISSUE THREAD

**Issue by zeppaman** [zeppaman/bashy#2]
Include a logging library for having file/console log. Enable logging by argument in the command. The library to use is : https://github.com/google/logger

**Comment by gfelixc** [comment]
@zeppaman can you assign me this?

**Comment by zeppaman** [comment]
@gfelixc sure. 
we have not a contributors file yet. let me know if you have trouble starting the project locally. basically, you have to clone and compile using commands from README.md.
+ @immenso

**Comment by zeppaman** [comment]
for what I undestrood @polletto is managing it. @polletto can you confirm you are in charge of this?

**Comment by polletto** [comment]
Yep i take it.
